#!/usr/bin/env -S uv run
"""
mail -- read-only mail viewer for every account, built on the Nylas Python SDK.

Read-only guarantee: the only API call this script makes is messages.list, so it
never sends, deletes, moves, or marks anything.

Usage:
    ./mail.py                             every account, newest 10 in the inbox
    ./mail.py -n 20                       newest 20 per account
    ./mail.py -u                          unread only
    ./mail.py -a outlook                  one account: outlook | gmail | pku | email
    ./mail.py -f dev                      one folder, by name
    ./mail.py -a outlook --all-folders    every folder (Outlook subfolders included)
    ./mail.py --days 3                    only mail received in the last 3 days
    ./mail.py --all --max 50              paginate, at most 50 per account
    ./mail.py --ids                       print message ids (for follow-up actions)
    ./mail.py -j                          JSON output for piping
    ./mail.py --refresh                   ignore the cached account/folder lists

Output legend:  U unread   S starred, followed by sender and subject.

Notes:
  * Folder names match case-insensitively, and a unique substring is enough.
  * A folder missing in one account skips that account only, and the exit code
    is 1 when any account failed, so callers can detect partial runs.
  * Cached ids self-heal: a stale folder id triggers one refresh and one retry.
  * Microsoft answers about 0.1-0.2s per message, so pages there are capped at
    50 and larger requests paginate; Google and IMAP are roughly ten times
    faster.
"""

import argparse
import json
import sys
import time
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, TypedDict, cast

import config
import nylib
from nylas.models.messages import ListMessagesQueryParams, Message

# Fields this view asks the API for. Everything else (notably the HTML body)
# stays on the server, which is where most of the payload saving comes from.
# The projection belongs to the view that needs it, not to the shared config.
SELECT = "id,grant_id,object,thread_id,subject,from,date,unread,starred,folders"

# Table layout is this view's own business, so the widths live here rather than
# in config.py.
SENDER_WIDTH = 26
STAMP_WIDTH = 11
ID_INDENT = " " * (STAMP_WIDTH + 7)


class MessageRow(TypedDict):
    """One message, flattened to the fields the display and JSON output need."""

    id: str
    thread_id: str | None
    date: int | None
    date_iso: str | None
    unread: bool
    starred: bool
    sender_name: str
    sender_email: str | None
    subject: str
    folder_names: list[str]


class AccountReport(TypedDict):
    """One mailbox worth of results, or the reason there are none."""

    email: str
    provider: str | None
    grant_status: str | None
    folder: str
    folder_id: str | None
    count: int
    messages: list[MessageRow]


@dataclass(frozen=True)
class Filters:
    """Server-side filters; only the ones the user asked for are sent."""

    unread: bool = False
    starred: bool = False
    days: int | None = None


@dataclass(frozen=True)
class Options:
    """Everything the read path needs, assembled once from the CLI."""

    account: str = "all"
    target: int = config.DEFAULT_MESSAGE_LIMIT
    filters: Filters = Filters()
    folder: str | None = None
    all_folders: bool = False
    refresh: bool = False
    ids: bool = False


def build_query(
    folder_id: str | None, limit: int, filters: Filters, page_token: str | None = None
) -> ListMessagesQueryParams:
    """Assemble the messages.list query parameters for one request.

    The cast is needed because the SDK builds ListMessagesQueryParams with a
    functional TypedDict that unpacks ListQueryParams at runtime, so the
    inherited keys (limit, page_token) are invisible to type checkers.
    """
    query: dict[str, Any] = {"limit": limit, "select": SELECT}
    if folder_id:
        query["in"] = folder_id
    if filters.unread:
        query["unread"] = True
    if filters.starred:
        query["starred"] = True
    if filters.days is not None:
        query["received_after"] = int(time.time()) - filters.days * 86400
    if page_token:
        query["page_token"] = page_token
    return cast(ListMessagesQueryParams, query)


def fetch_page(
    grant_id: str,
    folder_id: str | None,
    limit: int,
    filters: Filters,
    page_token: str | None = None,
) -> tuple[list[Message], str | None]:
    """One page of messages. Returns (messages, next_cursor)."""
    response = nylib.client().messages.list(
        identifier=grant_id,
        query_params=build_query(folder_id, limit, filters, page_token),
    )
    data, next_cursor = nylib.list_data(response)
    return data, next_cursor


def to_row(message: Message) -> MessageRow:
    """Flatten one SDK message into the row the display and JSON use."""
    # to_dict() is generated by the dataclasses_json decorator on the SDK model,
    # so it exists at runtime but is invisible to type checkers.
    data: dict[str, Any] = message.to_dict()  # pyright: ignore[reportAttributeAccessIssue]
    # The first sender, or an empty mapping when the API omits the field.
    sender = (data.get("from") or [{}])[0]
    # The cast is for the SDK's untyped payload: to_dict() yields Any | None
    # values, which pyright refuses to assign into a TypedDict field by field.
    return cast(
        MessageRow,
        {
            "id": data.get("id"),
            "thread_id": data.get("thread_id"),
            "date": data.get("date"),
            "date_iso": nylib.ts_iso(data.get("date")),
            "unread": bool(data.get("unread")),
            "starred": bool(data.get("starred")),
            "sender_name": str(
                sender.get("name") or sender.get("email") or "?"
            ).strip(),
            "sender_email": sender.get("email"),
            "subject": data.get("subject") or "",
            "folder_names": data.get("folders") or [],
        },
    )


def resolve_folder(
    grant: nylib.Grant, opts: Options, refresh: bool = False
) -> tuple[nylib.Folder | None, str, dict[str, str]]:
    """Decide which folder to read for one account.

    Returns (folder_or_None, label, folder_names_by_id). Raises LookupError when
    a requested folder name cannot be resolved in this account. `refresh` forces
    a fresh folder list, which is how a stale cached id is recovered from.
    """
    folders = nylib.load_folders(grant["id"], refresh=opts.refresh or refresh)
    by_id = {f["id"]: f["name"] for f in folders}

    if opts.all_folders:
        # No folder filter, but the id -> name map is still needed to label
        # each message with the folders it lives in.
        return None, "all folders", by_id

    if opts.folder:
        folder = nylib.resolve_named(folders, opts.folder, kind="folder")
        return folder, folder["name"], by_id

    inbox = nylib.find_inbox(folders)
    if inbox is None:
        return None, "all folders (no inbox detected)", by_id
    return inbox, inbox["name"], by_id


def read_messages(
    grant: nylib.Grant, folder: nylib.Folder | None, opts: Options
) -> list[MessageRow]:
    """Fetch up to the requested number of messages, paginating as needed.

    Both -n and --all end up here: the target is the requested limit either way.
    Pages are sized per provider (see nylib.page_limit) because Microsoft
    answers a large page far more slowly than Google or IMAP.
    """
    size = config.page_size(grant.get("provider"))
    rows: list[MessageRow] = []
    page_token: str | None = None
    while len(rows) < opts.target:
        want = min(size, opts.target - len(rows))
        messages, page_token = fetch_page(
            grant["id"],
            folder["id"] if folder else None,
            want,
            opts.filters,
            page_token,
        )
        rows.extend(to_row(message) for message in messages)
        if not messages or not page_token:
            break
    return rows


def fetch_account(grant: nylib.Grant, opts: Options) -> AccountReport:
    """Read one mailbox. Raises on failure; the caller isolates accounts."""
    folder, label, folders_by_id = resolve_folder(grant, opts)

    try:
        rows = read_messages(grant, folder, opts)
    except Exception as exc:  # retried below only when a cached folder id went stale
        if not (folder and opts.folder and nylib.is_not_found(exc)):
            raise
        # The cached folder id went stale (folder renamed or recreated): reread
        # the folder list and retry exactly once.
        folder, label, folders_by_id = resolve_folder(grant, opts, refresh=True)
        rows = read_messages(grant, folder, opts)

    rows.sort(key=lambda row: row["date"] or 0, reverse=True)
    for row in rows:
        row["folder_names"] = [
            folders_by_id.get(fid, fid) for fid in row["folder_names"]
        ]
    return {
        "email": grant["email"],
        "provider": grant.get("provider"),
        "grant_status": grant.get("grant_status"),
        "folder": label,
        "folder_id": folder["id"] if folder else None,
        "count": len(rows),
        "messages": rows,
    }


def print_account(report: AccountReport, opts: Options, term_width: int) -> None:
    """Render one mailbox as a plain-text block."""
    print(
        f"\n=== {report['email']} [{report['provider']}]"
        f" - folder: {report['folder']} - {report['count']} messages ==="
    )
    if not report["messages"]:
        print("  (no messages)")
        return

    for row in report["messages"]:
        mark = ("U" if row["unread"] else "-") + ("S" if row["starred"] else "-")
        tags = ""
        if opts.all_folders and row["folder_names"]:
            tags = "[" + ",".join(row["folder_names"]) + "] "
        used = STAMP_WIDTH + len(mark) + SENDER_WIDTH + 4
        subject = nylib.trunc(
            tags + (row["subject"] or "(no subject)"), max(20, term_width - used)
        )
        stamp = nylib.local_time(row["date"])
        date_label = stamp.strftime("%m-%d %H:%M") if stamp else "??-?? ??:??"
        print(
            f" {nylib.pad(date_label, STAMP_WIDTH)}"
            f" {mark}  {nylib.pad(row['sender_name'], SENDER_WIDTH)} {subject}"
        )
        if opts.ids:
            print(f"{ID_INDENT}id: {row['id']}")


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse and validate the command line."""
    parser = argparse.ArgumentParser(
        prog="mail",
        description="Read-only mail viewer (never sends, deletes, moves, or marks mail).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-a",
        "--account",
        default="all",
        help="account selector: all (default) | outlook | gmail | pku | email",
    )
    parser.add_argument(
        "-n",
        "--limit",
        type=int,
        help=f"messages per account (default {config.DEFAULT_MESSAGE_LIMIT})",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="paginate up to --max (default 200)",
    )
    parser.add_argument(
        "--max",
        type=int,
        default=config.DEFAULT_MESSAGE_MAX,
        help=f"upper bound per account when --all is used (default {config.DEFAULT_MESSAGE_MAX})",
    )
    parser.add_argument("-u", "--unread", action="store_true", help="unread only")
    parser.add_argument("-s", "--starred", action="store_true", help="starred only")
    parser.add_argument(
        "-f", "--folder", help="folder name (case-insensitive, substring allowed)"
    )
    parser.add_argument(
        "--all-folders",
        action="store_true",
        help="skip the folder filter and search every folder",
    )
    parser.add_argument(
        "--days",
        type=int,
        help="only mail received in the last N days (server-side filter)",
    )
    parser.add_argument("--ids", action="store_true", help="print message ids")
    parser.add_argument("-j", "--json", action="store_true", help="JSON output")
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="rebuild the cached account and folder lists",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=config.DEFAULT_WORKERS,
        help=f"concurrent accounts (default {config.DEFAULT_WORKERS})",
    )
    args = parser.parse_args(argv)

    if args.all and args.limit is not None:
        parser.error("--all cannot be combined with -n/--limit (use --max)")
    if args.all_folders and args.folder:
        parser.error("--all-folders cannot be combined with -f/--folder")
    if args.limit is not None and args.limit < 1:
        parser.error("-n/--limit must be positive")
    if args.all and args.max < 1:
        parser.error("--max must be positive")
    if args.days is not None and args.days < 0:
        parser.error("--days must not be negative")
    if args.workers < 1:
        parser.error("--workers must be positive")
    return args


def run(args: argparse.Namespace) -> int:
    """Read every selected account and report the result."""
    nylib.client()  # fail fast: one clean config error instead of one per account
    opts = Options(
        account=args.account,
        target=args.max if args.all else (args.limit or config.DEFAULT_MESSAGE_LIMIT),
        filters=Filters(unread=args.unread, starred=args.starred, days=args.days),
        folder=args.folder,
        all_folders=args.all_folders,
        refresh=args.refresh,
        ids=args.ids,
    )

    grants = nylib.load_grants(refresh=opts.refresh)
    targets, unknown = nylib.select_grants(grants, opts.account)

    errors: list[dict[str, str]] = [
        {"account": term, "error": "no account matches this selector"}
        for term in unknown
    ]
    for item in errors:
        print(f"! {item['account']}: {item['error']}", file=sys.stderr)
    if not targets and not errors:
        print("! no accounts available for this API key", file=sys.stderr)

    reports, failures = nylib.gather(
        lambda grant: fetch_account(grant, opts), targets, workers=args.workers
    )
    for grant, failure in zip(targets, failures):
        if failure is not None:
            message = nylib.describe_error(failure)
            errors.append({"account": grant["email"], "error": message})
            print(f"! {grant['email']}: {message}", file=sys.stderr)

    accounts: list[Any] = [report for report in reports if report is not None]

    if args.json:
        print(
            json.dumps(
                {
                    "generated_at": nylib.now_iso(),
                    "accounts": accounts,
                    "errors": errors,
                },
                ensure_ascii=False,
                indent=2,
            )
        )
    else:
        if not accounts:
            print("! nothing to show", file=sys.stderr)
        width = nylib.terminal_width()
        for report in accounts:
            print_account(report, opts, width)

    return 1 if errors else 0


def main() -> int:
    """Entry point: turn a missing API key into a clean message and exit code."""
    args = parse_args()
    try:
        return run(args)
    except nylib.ConfigError as exc:
        print(f"! {exc}".replace("\n", "\n  "), file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
